version: '3'
services:
  prometheus :
    container_name : bs-rst-dev-hello-world-prometheus
    image : prom/prometheus:v2.37.1
    volumes :
      - ./docker/prometheus/:/etc/prometheus/
    command :
      - '--config.file=/etc/prometheus/prometheus.yml'
    # On MacOS, remove next line and replace localhost by host.docker.internal in docker/prometheus/prometheus.yml and
    # docker/grafana/provisioning/datasources/datasource.yml
    network_mode: host # to test locally running service
  grafana :
    container_name : bs-rst-dev-hello-world-grafana
    image : grafana/grafana:8.5.13
    volumes :
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
    environment :
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    # On MacOS, remove next line and replace localhost by host.docker.internal in docker/prometheus/prometheus.yml and
    # docker/grafana/provisioning/datasources/datasource.yml
    network_mode: host # to test locally running service
