ujar :
  build :
    description : '@project.description@'
    relative-path : ${SWAGGER_UI_RELATIVE_PATH:}
    version : '@project.version@'

git :
  build_time : '@git.build.time@'
  commit : '@git.commit.id.abbrev@'
info :
  app :
    build_time : ${git.build_time}
    description : '@project.description@'
    git_commit : ${git.commit}
    name : '@project.name@'
    version : '@project.version@'

logging :
  level :
    ROOT : ${LOGGING_LEVEL_ROOT:INFO}

management :
  health :
    livenessstate :
      enabled : true
    readinessstate :
      enabled : true
  endpoint :
    health :
      enabled : true
      show-details : always
      probes :
        enabled : true
    info :
      enabled : true
    prometheus :
      enabled : true
  endpoints :
    enabled-by-default : false
    web :
      exposure :
        include : health, prometheus, info, openapi, swagger-ui
  info :
    env :
      enabled : true

  server :
    add-application-context-header : true
server :
  port : ${SERVER_PORT:8080}
  shutdown : graceful
spring :
  application :
    name : quickstart-restful-hello-world
  devtools :
    add-properties : false
    livereload :
      enabled : false
    restart :
      enabled : false
  jackson :
    default-property-inclusion : NON_NULL
  lifecycle :
    timeout-per-shutdown-phase : ${TIMEOUT_PER_SHUTDOWN:20s}

springdoc :
  show-actuator : false
  swagger-ui :
    config-url : ${SWAGGER_UI_RELATIVE_PATH:/}v3/api-docs/swagger-config
    url : ${SWAGGER_UI_RELATIVE_PATH:/}v3/api-docs
