management:
    endpoints:
        enabled-by-default: true
spring:
    devtools:
        add-properties: true
        livereload:
            enabled: true
        restart:
            enabled: true
