apiVersion : networking.k8s.io/v1
kind : Ingress
metadata :
  name : gateway-ingress
  annotations :
    kubernetes.io/ingress.class : nginx
    nginx.ingress.kubernetes.io/backend-protocol : "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target : /$2
spec :
  rules :
    - host : hello-world.info
      http :
        paths :
          - path : /hello(/|$)(.*)
            pathType : Prefix
            backend :
              service :
                name : hello-world
                port :
                  number : 8080
